# Generated by Django 5.1.4 on 2025-01-28 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_author_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='new_app.author'),
        ),
    ]
