# Generated by Django 5.1.4 on 2025-02-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_author_is_approved_book_is_approved_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
