# Generated by Django 5.1.4 on 2025-02-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_reader_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_phone_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='reader',
            name='reader_phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
