# Generated by Django 5.1.4 on 2025-02-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_alter_author_author_phone_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
