# Generated by Django 5.1.4 on 2025-09-12 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0007_alter_borrow_borrow_date_alter_borrow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('borrowed', 'borrowed'), ('returned', 'returned')], default='borrowed', max_length=10),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='new_app.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.reader')),
            ],
        ),
    ]
