# Generated by Django 5.1.4 on 2025-09-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0010_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_phone_no',
            field=models.CharField(max_length=12),
        ),
    ]
