# Generated by Django 5.1.4 on 2025-09-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0011_author_is_rejected_alter_author_author_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reader',
            name='reader_phone_no',
            field=models.CharField(max_length=12),
        ),
    ]
